### ISSUE TITLE
关于项目文件结构布局的一些可能

### ISSUE THREAD

**Issue by Guanda0120** [DViridescent/AddinsWithWpfSample#1]
当业务信息强依赖于某些软件的数据类型时候，王老师觉得应该如何架构项目呢。
考虑这样一种业务场景。业务需要记录Rhino中的Brep信息。或者需要使用RC中的原生函数。
是不是`./Rhino/` 中应该有一个项目文件夹`.\Rhino\SomeBusiness\`中有一个SomeBusiness.csproj作为底层依赖呢

**Comment by DViridescent** [comment]
我觉得这里是两个问题

## 问题1：如果Rhino有独立功能，有独立的UI和对应的实现怎么办

> 太长不看：需要修改项目结构，做一条Rhino独立的项目依赖链条

当前仓库的示例是针对三个软件共享同一套UI和同一套功能的场景

当需要每个软件有各自独立的UI（例如RhinoView、RhinoViewModel）时，应该有另外的项目结构，大致可能是：
- Rhino项目不再直接依赖`Sample.UI.WPF`，而是改为依赖`Sample.UI.WPF.Rhino`
- 把`Sample.Core`、`Sample.UI`和`Sample.UI.WPF`各自拆成三份（三个软件各一份），然后三个项目（假设其中一个ViewModel层的项目叫做`Sample.UI.Rhino`）去依赖一个独立的`Sample.UI.Base`或者`Sample.UI.Components`，再分别依赖`Sample.Core`
- `Sample.UI.Rhino`还需要依赖特定与Rhino的一些业务定义，`Sample.Core.Rhino`

总之，相当于把View、ViewModel、Core都拆成三份，但它们在各自那一层还可以通过某些公共项目共享一部分公共代码。

## 问题2：关于UI的代码（View和ViewModel）是否有必要知道执行Services类中的具体数据类型

> 太长不看：UI层只接触业务层的抽象，只使用接口

我不认为在ViewModel层的代码里需要用到`Rhino.Geometry.Brep`这样的对象，它也不应该依赖`Rhino.Common`，无论这是不是一个Rhino插件的特有UI和功能

可能的做法：
- 在属于Rhino的Core项目（`Sample.Core.Rhino`）中定义`IBrepService`接口和`IBrepData`接口
- `IBrepService`中可能有这些方法
    - 获取Brep：返回`IBrepData`，它携带Brep数据
    - 保存Brep：输入`IBrepData`和filePath，把对应Brep数据序列化到文件中

在此处，ViewModel层操作的是接口，所以它只需要依赖Core（的抽象定义）
然后会有对接口的实现，假设把实现放到一个单独的项目里，那么这个实现了`IBrepService`接口的项目会依赖Core（接口定义），然后最后被属于插件入口的那个项目依赖（或者也可以像现在这样和入口整合到一起——`Sample.Rhino`下有一个`Sample.Rhino.Services`命名空间）

**Comment by Guanda0120** [comment]
第二点我觉得没什么问题。第一点我的理解是Core中有一个专门记录Rhino相关的业务信息的类库是这样么~

**Comment by DViridescent** [comment]
差不多

**Comment by Guanda0120** [comment]
感谢王老师
